name: CI - Train, Validate & Push Model

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train_and_push:
    runs-on: ubuntu-latest
    env:
      MLFLOW_TRACKING_URI: file://./mlruns
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install system deps
        run: |
          sudo apt-get update -y
          sudo apt-get install -y git-lfs

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run training script
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
        run: |
          mkdir -p models
          python src/models/train.py --train data/processed/train.csv --test data/processed/test.csv --output models/best_model.joblib --experiment "ci-train"

      - name: Push model to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python src/deployment/push_model_to_hf.py --model-path models/best_model.joblib --repo-id rohanchemical/tourism-wellness-model --token ${{ secrets.HF_TOKEN }}

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: model-and-metrics
          path: |
            models/best_model.joblib
            artifacts/metrics.json
            mlruns
